/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

/**
 * @since 2020
 * @author Huawei DTSE India
 */
public class CoursesCodelabDetailsTable extends CloudDBZoneObject {
    @PrimaryKey
    private Integer codeLabId;

    private Integer courseId;

    private String codeLabUrl;

    private String codeLabContentA;

    private String codeLabContentB;

    private String codeLabContentC;

    private String codeLabContentD;

    private String codeLabContentE;

    private String codeLabContentF;

    private String codeLabContentG;

    private String codeLabContentH;

    private String codeLabContentI;

    private String codeLabContentJ;

    private String codeLabContentK;

    private String codeLabContentL;

    public CoursesCodelabDetailsTable() {
        super();
    }

    public void setCodeLabId(Integer codeLabId) {
        this.codeLabId = codeLabId;
    }

    public Integer getCodeLabId() {
        return codeLabId;
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public Integer getCourseId() {
        return courseId;
    }

    public void setCodeLabUrl(String codeLabUrl) {
        this.codeLabUrl = codeLabUrl;
    }

    public String getCodeLabUrl() {
        return codeLabUrl;
    }

    public void setCodeLabContentA(String codeLabContentA) {
        this.codeLabContentA = codeLabContentA;
    }

    public String getCodeLabContentA() {
        return codeLabContentA;
    }

    public void setCodeLabContentB(String codeLabContentB) {
        this.codeLabContentB = codeLabContentB;
    }

    public String getCodeLabContentB() {
        return codeLabContentB;
    }

    public void setCodeLabContentC(String codeLabContentC) {
        this.codeLabContentC = codeLabContentC;
    }

    public String getCodeLabContentC() {
        return codeLabContentC;
    }

    public void setCodeLabContentD(String codeLabContentD) {
        this.codeLabContentD = codeLabContentD;
    }

    public String getCodeLabContentD() {
        return codeLabContentD;
    }

    public void setCodeLabContentE(String codeLabContentE) {
        this.codeLabContentE = codeLabContentE;
    }

    public String getCodeLabContentE() {
        return codeLabContentE;
    }

    public void setCodeLabContentF(String codeLabContentF) {
        this.codeLabContentF = codeLabContentF;
    }

    public String getCodeLabContentF() {
        return codeLabContentF;
    }

    public void setCodeLabContentG(String codeLabContentG) {
        this.codeLabContentG = codeLabContentG;
    }

    public String getCodeLabContentG() {
        return codeLabContentG;
    }

    public void setCodeLabContentH(String codeLabContentH) {
        this.codeLabContentH = codeLabContentH;
    }

    public String getCodeLabContentH() {
        return codeLabContentH;
    }

    public void setCodeLabContentI(String codeLabContentI) {
        this.codeLabContentI = codeLabContentI;
    }

    public String getCodeLabContentI() {
        return codeLabContentI;
    }

    public void setCodeLabContentJ(String codeLabContentJ) {
        this.codeLabContentJ = codeLabContentJ;
    }

    public String getCodeLabContentJ() {
        return codeLabContentJ;
    }

    public void setCodeLabContentK(String codeLabContentK) {
        this.codeLabContentK = codeLabContentK;
    }

    public String getCodeLabContentK() {
        return codeLabContentK;
    }

    public void setCodeLabContentL(String codeLabContentL) {
        this.codeLabContentL = codeLabContentL;
    }

    public String getCodeLabContentL() {
        return codeLabContentL;
    }
}
