/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

/**
 * @since 2020
 * @author Huawei DTSE India
 */
public class CoursesDocTable extends CloudDBZoneObject {
    @PrimaryKey
    private String courseName;

    private String docTableOfContent;

    private String docDescription;

    private String docUrl;

    private String docCodeLabUrl;

    private String docPlatformsIds;

    public CoursesDocTable() {
        super();
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setDocTableOfContent(String docTableOfContent) {
        this.docTableOfContent = docTableOfContent;
    }

    public String getDocTableOfContent() {
        return docTableOfContent;
    }

    public void setDocDescription(String docDescription) {
        this.docDescription = docDescription;
    }

    public String getDocDescription() {
        return docDescription;
    }

    public void setDocUrl(String docUrl) {
        this.docUrl = docUrl;
    }

    public String getDocUrl() {
        return docUrl;
    }

    public void setDocCodeLabUrl(String docCodeLabUrl) {
        this.docCodeLabUrl = docCodeLabUrl;
    }

    public String getDocCodeLabUrl() {
        return docCodeLabUrl;
    }

    public void setDocPlatformsIds(String docPlatformsIds) {
        this.docPlatformsIds = docPlatformsIds;
    }

    public String getDocPlatformsIds() {
        return docPlatformsIds;
    }
}
