/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

/**
 * @since 2020
 * @author Huawei DTSE India
 */
public class CourseDetailsTable extends CloudDBZoneObject {
    @PrimaryKey
    private Integer courseId;

    private Integer mainCategoryId;

    private Integer subCategoryId;

    private Integer courseTypeId;

    private Integer coursePriceId;

    private String courseDocId;

    private String courseNmae;

    private String courseDesc;

    private String courseImageUrl;

    private String courseVideoUrl;

    private String courseAudioUrl;

    private String courseAuthor;

    private String coursePlaformId;

    private Integer courseCodelabId;

    private Integer courseContentId;

    public CourseDetailsTable() {
        super();
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public Integer getCourseId() {
        return courseId;
    }

    public void setMainCategoryId(Integer mainCategoryId) {
        this.mainCategoryId = mainCategoryId;
    }

    public Integer getMainCategoryId() {
        return mainCategoryId;
    }

    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    public Integer getSubCategoryId() {
        return subCategoryId;
    }

    public void setCourseTypeId(Integer courseTypeId) {
        this.courseTypeId = courseTypeId;
    }

    public Integer getCourseTypeId() {
        return courseTypeId;
    }

    public void setCoursePriceId(Integer coursePriceId) {
        this.coursePriceId = coursePriceId;
    }

    public Integer getCoursePriceId() {
        return coursePriceId;
    }

    public void setCourseDocId(String courseDocId) {
        this.courseDocId = courseDocId;
    }

    public String getCourseDocId() {
        return courseDocId;
    }

    public void setCourseNmae(String courseNmae) {
        this.courseNmae = courseNmae;
    }

    public String getCourseNmae() {
        return courseNmae;
    }

    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc;
    }

    public String getCourseDesc() {
        return courseDesc;
    }

    public void setCourseImageUrl(String courseImageUrl) {
        this.courseImageUrl = courseImageUrl;
    }

    public String getCourseImageUrl() {
        return courseImageUrl;
    }

    public void setCourseVideoUrl(String courseVideoUrl) {
        this.courseVideoUrl = courseVideoUrl;
    }

    public String getCourseVideoUrl() {
        return courseVideoUrl;
    }

    public void setCourseAudioUrl(String courseAudioUrl) {
        this.courseAudioUrl = courseAudioUrl;
    }

    public String getCourseAudioUrl() {
        return courseAudioUrl;
    }

    public void setCourseAuthor(String courseAuthor) {
        this.courseAuthor = courseAuthor;
    }

    public String getCourseAuthor() {
        return courseAuthor;
    }

    public void setCoursePlaformId(String coursePlaformId) {
        this.coursePlaformId = coursePlaformId;
    }

    public String getCoursePlaformId() {
        return coursePlaformId;
    }

    public void setCourseCodelabId(Integer courseCodelabId) {
        this.courseCodelabId = courseCodelabId;
    }

    public Integer getCourseCodelabId() {
        return courseCodelabId;
    }

    public void setCourseContentId(Integer courseContentId) {
        this.courseContentId = courseContentId;
    }

    public Integer getCourseContentId() {
        return courseContentId;
    }
}
