/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

/**
 * @since 2020
 * @author Huawei DTSE India
 */
public class ExamTable extends CloudDBZoneObject {
    @PrimaryKey
    private Integer examId;

    private Integer courseId;

    private String examName;

    private String examDescription;

    private Integer examDuration;

    private Integer examNoOfQuestions;

    private Integer examTotalMarks;

    private Integer examPassMarks;

    private Integer examAttempts;

    public ExamTable() {
        super();
    }

    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    public Integer getExamId() {
        return examId;
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public Integer getCourseId() {
        return courseId;
    }

    public void setExamName(String examName) {
        this.examName = examName;
    }

    public String getExamName() {
        return examName;
    }

    public void setExamDescription(String examDescription) {
        this.examDescription = examDescription;
    }

    public String getExamDescription() {
        return examDescription;
    }

    public void setExamDuration(Integer examDuration) {
        this.examDuration = examDuration;
    }

    public Integer getExamDuration() {
        return examDuration;
    }

    public void setExamNoOfQuestions(Integer examNoOfQuestions) {
        this.examNoOfQuestions = examNoOfQuestions;
    }

    public Integer getExamNoOfQuestions() {
        return examNoOfQuestions;
    }

    public void setExamTotalMarks(Integer examTotalMarks) {
        this.examTotalMarks = examTotalMarks;
    }

    public Integer getExamTotalMarks() {
        return examTotalMarks;
    }

    public void setExamPassMarks(Integer examPassMarks) {
        this.examPassMarks = examPassMarks;
    }

    public Integer getExamPassMarks() {
        return examPassMarks;
    }

    public void setExamAttempts(Integer examAttempts) {
        this.examAttempts = examAttempts;
    }

    public Integer getExamAttempts() {
        return examAttempts;
    }
}
