/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.kotlin.database.tables

import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey

/**
 * @since 2020
 * @author Huawei DTSE India
 */
class CoursesDocTable : CloudDBZoneObject() {
    @PrimaryKey
    var courseName: String? = null
    var docTableOfContent: String? = null
    var docDescription: String? = null
    var docUrl: String? = null
    var docCodeLabUrl: String? = null
    var docPlatformsIds: String? = null

}