/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.kotlin.database.tables

import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey

/**
 * @since 2020
 * @author Huawei DTSE India
 */
class CoursesCodelabDetailsTable : CloudDBZoneObject() {
    @PrimaryKey
    var codeLabId: Int? = null
    var courseId: Int? = null
    var codeLabUrl: String? = null
    var codeLabContentA: String? = null
    var codeLabContentB: String? = null
    var codeLabContentC: String? = null
    var codeLabContentD: String? = null
    var codeLabContentE: String? = null
    var codeLabContentF: String? = null
    var codeLabContentG: String? = null
    var codeLabContentH: String? = null
    var codeLabContentI: String? = null
    var codeLabContentJ: String? = null
    var codeLabContentK: String? = null
    var codeLabContentL: String? = null

}