/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.kotlin.database.tables

import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey

/**
 * @since 2020
 * @author Huawei DTSE India
 */
class CourseContentTable : CloudDBZoneObject() {
    @PrimaryKey
    var courseContentId: Int? = null
    var courseId: Long? = null
    var contentA: String? = null
    var contentB: String? = null
    var contentC: String? = null
    var contentD: String? = null
    var contentE: String? = null
    var contentF: String? = null
    var contentG: String? = null
    var contentH: String? = null
    var contentI: String? = null
    var contentJ: String? = null
    var contentK: String? = null
    var contentL: String? = null

}