/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.kotlin.database.tables

import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey

/**
 * @since 2020
 * @author Huawei DTSE India
 */
class ExamTable : CloudDBZoneObject() {
    @PrimaryKey
    var examId: Int? = null
    var courseId: Int? = null
    var examName: String? = null
    var examDescription: String? = null
    var examDuration: Int? = null
    var examNoOfQuestions: Int? = null
    var examTotalMarks: Int? = null
    var examPassMarks: Int? = null
    var examAttempts: Int? = null

}