/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.kotlin.database.tables

import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey

/**
 * @since 2020
 * @author Huawei DTSE India
 */
class QuestionsTable : CloudDBZoneObject() {
    @PrimaryKey
    var questionId: Long? = null
    var examId: Int? = null
    var courseId: Int? = null
    var question: String? = null
    var optionA: String? = null
    var optionB: String? = null
    var optionC: String? = null
    var optionD: String? = null
    var marks: Int? = null
    var answer: String? = null

}