/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.training.kotlin.database.tables

import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey

/**
 * @since 2020
 * @author Huawei DTSE India
 */
class UsersInfoTable : CloudDBZoneObject() {
    @PrimaryKey
    var userId: String? = null
    var firstName: String? = null
    var lastName: String? = null
    var displayName: String? = null
    var email: String? = null
    var mobile: String? = null
    var userImageUrl: String? = null

}